map = {
    systems: [
        {
            name: "Cevis",
            pos: {x: 0, y: 0},
            asteroidBelt: {
                quant: 2000,
                beginRadius: 1700,
                endRadius: 2200,
                size: 3,
            },
            star: {
                type: "single",
                name: "Cevis Star",
                size: 1200,
                strength: 12000,
                maxStrength: 0.02,
                auraSize: 15,
                featheringSize: 7,
                color: "#2255dd",
                auraBeginColor: "#aaaaff28",
                auraEndColor: "#0000ff00",
                cracksColor: "#3366cc",
            },
            planets: [
                {
                    name: "Pheon K61",
                    orbitDuration: 1 / (Math.random() * 0.009 + 0.001),
                    orbitPhase: Math.random() * 2 * Math.PI,
                    orbitRadius: 1200,
                    strength: 200,
                    maxStrength: 0.02,
                    size: 120,
                    auraSize: 15,
                    featheringSize: 7,
                    color: "#2255dd",
                    auraBeginColor: "#aaaaff28",
                    auraEndColor: "#0000ff00",
                    cracksColor: "#3366cc",
                },
                {
                    name: "Ithars",
                    orbitDuration: 1 / (Math.random() * 0.009 + 0.001),
                    orbitPhase: Math.random() * 2 * Math.PI,
                    orbitRadius: 1600,
                    strength: 200,
                    maxStrength: 0.02,
                    size: 200,
                    auraSize: 4,
                    featheringSize: 0,
                    color: "#000000",
                    auraBeginColor: "#000000ff",
                    auraEndColor: "#22222200",
                    cracksColor: "#111111",
                },
                {
                    name: "Zoxenov",
                    orbitDuration: 1 / (Math.random() * 0.009 + 0.001),
                    orbitPhase: Math.random() * 2 * Math.PI,
                    orbitRadius: 2300,
                    strength: 400,
                    maxStrength: 0.05,
                    size: 400,
                    auraSize: 8,
                    featheringSize: 3,
                    color: "#cc2233",
                    auraBeginColor: "#cc229955",
                    auraEndColor: "#cc229900",
                    cracksColor: "#ff4455",
                },
            ],
        },
        {
            name: "R41N-B0w",
            pos: {x: 3500, y: 1700},
            planets: [
                {
                    name: "R41N-B0w C1",
                    orbitDuration: 50,
                    orbitPhase: 3,
                    orbitRadius: 100,
                    strength: 50,
                    maxStrength: 0.02,
                    size: 40,
                    auraSize: 3,
                    featheringSize: 5,
                    color: "#9400d3",
                    auraBeginColor: "#9400d333",
                    auraEndColor: "#9400d300",
                },
                {
                    name: "R41N-B0w C2",
                    orbitDuration: 50,
                    orbitPhase: 2.5,
                    orbitRadius: 150,
                    strength: 50,
                    maxStrength: 0.02,
                    size: 50,
                    auraSize: 3,
                    featheringSize: 5,
                    color: "#4b0082",
                    auraBeginColor: "#4b008233",
                    auraEndColor: "#4b008200",
                },
                {
                    name: "R41nb0w C3",
                    orbitDuration: 50,
                    orbitPhase: 2,
                    orbitRadius: 210,
                    strength: 50,
                    maxStrength: 0.02,
                    size: 60,
                    auraSize: 3,
                    featheringSize: 5,
                    color: "#0000ff",
                    auraBeginColor: "#0000ff33",
                    auraEndColor: "#0000ff00",
                    cracksColor: "#2222dd",
                },
                {
                    name: "R41N-B0w C4",
                    orbitDuration: 50,
                    orbitPhase: 1.5,
                    orbitRadius: 280,
                    strength: 50,
                    maxStrength: 0.02,
                    size: 70,
                    auraSize: 3,
                    featheringSize: 5,
                    color: "#00ff00",
                    auraBeginColor: "#00ff0033",
                    auraEndColor: "#00ff0000",
                    cracksColor: "#22dd22",
                },
                {
                    name: "R41N-B0w C5",
                    orbitDuration: 50,
                    orbitPhase: 1,
                    orbitRadius: 360,
                    strength: 50,
                    maxStrength: 0.02,
                    size: 80,
                    auraSize: 3,
                    featheringSize: 5,
                    color: "#ffff00",
                    auraBeginColor: "#ffff0033",
                    auraEndColor: "#ffff0000",
                    cracksColor: "#dddd22",
                },
                {
                    name: "R41N-B0w C6",
                    orbitDuration: 50,
                    orbitPhase: 0.5,
                    orbitRadius: 450,
                    strength: 50,
                    maxStrength: 0.02,
                    size: 90,
                    auraSize: 3,
                    featheringSize: 5,
                    color: "#ff7f00",
                    auraBeginColor: "#ff7f0033",
                    auraEndColor: "#ff7f0000",
                    cracksColor: "#dd5f22",
                },
                {
                    name: "R41N-B0w C7",
                    orbitDuration: 50,
                    orbitPhase: 0,
                    orbitRadius: 550,
                    strength: 50,
                    maxStrength: 0.02,
                    size: 100,
                    auraSize: 3,
                    featheringSize: 5,
                    color: "#ff0000",
                    auraBeginColor: "#ff000033",
                    auraEndColor: "#ff000000",
                    cracksColor: "#dd2222",
                },
            ],
        },
    ],
}
